### ISSUE TITLE
您好，我对您的插件非常感兴趣，同时也做了一些修改

### ISSUE THREAD

**Issue by sishenhei7** [RyoHina/chrome_plugin_zhihu_adblock#2]
我做了如下修改：
1.删掉了 jquery，使用原生 js 操作 dom
2.增加 createFuckAd 函数，更容易扩展
3. chrome. extension.getURL 不建议使用了，我替换成了 chrome.runtime.getURL
4.使用了 onload 事件确保广告图片已经加载

代码我提了pr：https://github.com/RyoHina/chrome_plugin_zhihu_adblock/pull/3

**Comment by RyoHina** [comment]
pr已接受  #3

**Comment by kyle-go** [comment]
pr已接受 #3
